all : slide04 slide09 slide10 slide11 slide13 slide20 slide21 slide22 slide24 \
      slide29 slide30 slide31 slide32

slide04 : slide04.cpp
	g++ $< -o $@

slide09 : slide09.cpp
	g++ $< -o $@

slide10 : slide10.cpp
	g++ $< -o $@

slide11 : slide11.cpp
	g++ $< -o $@

slide13 : slide13.cpp
	g++ $< -o $@

slide20 : slide20.cpp
	g++ $< -o $@

slide21 : slide21.cpp
	g++ $< -o $@

slide22 : slide22.cpp
	g++ $< -o $@

slide24 : slide24.cpp
	g++ $< -o $@

slide29 : slide29.cpp
	g++ $< -o $@

slide30 : slide30.cpp
	g++ $< -o $@

slide31 : slide31.cpp
	g++ $< -o $@

slide32 : slide32.cpp
	g++ $< -o $@

clean :
	rm -f slide04 slide09 slide10 slide11 slide13 slide20 slide21 \
          slide22 slide24 slide29 slide30 slide31 slide32 *~


