all : slide02 slide03 slide05 slide06 slide07 slide09 slide10 slide11 \
      slide12 slide14 slide16 slide18 slide19 slide20


slide02 : slide02.cpp
	g++ $< -o $@

slide03 : slide03.cpp
	g++ $< -o $@

slide05 : slide05.cpp
	g++ $< -o $@

slide06 : slide06.cpp
	g++ $< -o $@

slide07 : slide07.cpp
	g++ $< -o $@

slide09 : slide09.cpp
	g++ $< -o $@

slide10 : slide10.cpp
	g++ $< -o $@

slide11 : slide11.cpp
	g++ $< -o $@

slide12 : slide12.cpp
	g++ $< -o $@

slide14 : slide14.cpp
	g++ $< -o $@

slide16 : slide16.cpp
	g++ $< -o $@

slide18 : slide18.cpp
	g++ $< -o $@

slide19 : slide19.cpp
	g++ $< -o $@

slide20 : slide20.cpp
	g++ $< -o $@


clean :
	rm -f slide02 slide03 slide05 slide06 slide07 slide09 slide10 slide11 \
          slide12 slide14 slide16 slide18 slide19 slide20 *~
